### ISSUE TITLE
Error in you Maven dependency example - README.md

### ISSUE THREAD

**Issue by orby** [beekpr/ssllabs#3]
Your maven dependency example in README.md should be with `<type>`jar`<type>`, not  `<type>`pom`<type>`. Since jar is default you can actually omit `<type>`.

And the version in your example says `1.0.1`, but you have released version `1.0.3`

So this is correct:
```
<dependency>
  <groupId>io.beekeeper.ssllabs</groupId>
  <artifactId>ssllabs-junit</artifactId>
  <version>1.0.3</version>
</dependency>
```

**Comment by Wattos** [comment]
Hi,

I am sorry for the rather late response, I must have missed the email notification. I will perform the updates ASAP.

**Comment by Wattos** [comment]
@orby 

Thanks, I updated the README accordingly. Thanks again for the info
